### ISSUE TITLE
Is your work supported by Vonage?

### ISSUE THREAD

**Issue by hakakou** [AndreiMisiukevich/Xamarin.Forms.Vonage#12]
I have downloaded the library and working example, and this is really wonderful! I want to build on the example for my contract project.

I was wondering about the following as Vonage is of course a payed service: Is your work supported also by Vonage, or are you simply maintaining this Xamarin.Forms port on your own? 

I am asking this of course just to know how well this port will be maintained, in case for example you don't have time or lose interest.

**Comment by AndreiMisiukevich** [comment]
Hi @hakakou

No, I did this project on my own in my spare time.
I am neither employed nor contracted in Vonage.

So, unfortunately, there are no guarantees that I will continue to support this project in the future.
But fairly speaking, the code is pretty simple. it's based on another xamarin package (which is platform-specific).
This project is just xamarin.forms wrapper

**Comment by hakakou** [comment]
OK thank you very much! I will fork and use in my project. If I add any functionality I'll do a pull request.
