### ISSUE TITLE
Android 13 - WRITE_EXTERNAL_STORAGE 

### ISSUE THREAD

**Issue by walnut-co** [AndreiMisiukevich/Xamarin.Forms.Vonage#13]
in android 13 - WRITE_EXTERNAL_STORAGE permission is causing issue, session never starts.
This permission always returns false/denied.

and new permissions may be required
`<uses-permission android:name="android.permission.READ_MEDIA_AUDIO" />
<uses-permission android:name="android.permission.READ_MEDIA_IMAGES" />
<uses-permission android:name="android.permission.READ_MEDIA_VIDEO" />`

any chance of updating this ?

**Comment by AndreiMisiukevich** [comment]
Try

```csharp
CrossVonage.Current.Permissions = VonagePermission.Camera | VonagePermission.RecordAudio | VonagePermission.ModifyAudioSettings | VonagePermission.Bluetooth;
```

**Comment by walnut-co** [comment]
I have sent you new pull request, please check and merge if possible and all good.

**Comment by AndreiMisiukevich** [comment]
1.1.5
