### ISSUE TITLE
[Query] Can you add VOIP Calling sample

### ISSUE THREAD

**Issue by WiproSarthak** [AndreiMisiukevich/Xamarin.Forms.Vonage#2]
Hi @AndreiMisiukevich  I need to implement VOIP calling functionality only.No t able to figure out how to achieve using this library.
I can hide publisher and subscriber view but still this will be not voice call right
Can you give me some hints

**Comment by AndreiMisiukevich** [comment]
Hi @WiproSarthak 

```csharp
CrossVonage.Current.IsVideoPublishingEnabled = false;
CrossVonage.Current.IsVideoSubscriptionEnabled = false;
CrossVonage.Current.Permissions = VonagePermission.RecordAudio;
```

Try this
