### ISSUE TITLE
com.opentok.android.Camera2VideoCapturer$Camera2Exception: CAMERA_DISABLED (1): validateClientPermissionsLocked:1426: Caller "com.package" (PID 10286, UID 7363) cannot open camera "1" from background (calling UID 10286 proc state 11)

### ISSUE THREAD

**Issue by balu-m** [AndreiMisiukevich/Xamarin.Forms.Vonage#3]
App Crashed with fallowing error.

Test case: on video call for 5 mins ,then background the app after few seconds forground then app crashing

com.opentok.android.Camera2VideoCapturer$Camera2Exception: CAMERA_DISABLED (1): validateClientPermissionsLocked:1426: Caller "com.package" (PID 10286, UID 7363) cannot open camera "1" from background (calling UID 10286 proc state 11)

com.opentok.android.Camera2VideoCapturer.initCamera
com.opentok.android.Camera2VideoCapturer.a
com.opentok.android.Camera2VideoCapturer.lambda$EOJ6zJ_KyEal1aLQznxfTJOPcJc
com.opentok.android.-$$Lambda$Camera2VideoCapturer$EOJ6zJ_KyEal1aLQznxfTJOPcJc.run
com.opentok.android.Camera2VideoCapturer$4.onClosed
android.hardware.camera2.impl.CameraDeviceImpl$5.run CameraDeviceImpl.java:214
android.os.Handler.handleCallback Handler.java:883
android.os.Handler.dispatchMessage Handler.java:100
android.os.Looper.loop Looper.java:237
android.app.ActivityThread.main ActivityThread.java:8107
java.lang.reflect.Method.invoke Method.java
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run RuntimeInit.java:496
com.android.internal.os.ZygoteInit.main ZygoteInit.java:1100

**Comment by AndreiMisiukevich** [comment]
Hi @balu-m 
Try to disable video when going to background and enable it again when the foreground

```csharp
CrossVonage.Current.IsVideoPublishingEnabled = false;
CrossVonage.Current.IsVideoSubscriptionEnabled = false;
```

**Comment by balu-m** [comment]
@AndreiMisiukevich thanks for response. i'll try
