### ISSUE TITLE
Chat History

### ISSUE THREAD

**Issue by ChelseaChiu** [AndreiMisiukevich/Xamarin.Forms.Vonage#7]
Where the Chat history stored? Will we be able to retrieve them per sessionId?

**Comment by AndreiMisiukevich** [comment]
Hi
Good question, I don't know honestly speaking (I presume Vonage stores them for sure). But my plug-in doesn't provide this feature (yet)

**Comment by AndreiMisiukevich** [comment]
I think it won't be implemented unless someone submit a PR
