### ISSUE TITLE
support latest Xamarin.Forms nugget

### ISSUE THREAD

**Issue by ChelseaChiu** [AndreiMisiukevich/Xamarin.Forms.Vonage#8]
Hi,

I have downloaded this sample code and tried it out. Everything works fine.
But after I update and NuGet package of Xamarin.Forms and Xamarin.Essentials etc, the remoteView(SubscriptionView) seems not working properly.
Would you be able to look into that?

**Comment by AndreiMisiukevich** [comment]
Hi @ChelseaChiu thanks for reporting this
Unfortunately, I don't have enough time now... Please feel free to debug this issue yourself and post a PR. I will review and merge it with pleasure :)

**Comment by AndreiMisiukevich** [comment]
please check latest nuget and let me know
